### ISSUE TITLE
Graficzne profile

### ISSUE THREAD

**Issue by Daste745** [strata-czasu/hashira#8]
Wątek: https://discord.com/channels/1198978337150881812/1237712430449033301
Design: https://www.figma.com/design/neyuacjg4ptcwIZyfTMQhh/Profile-graficzne-(Copy)

Profile userów w graficznej formie.

# TODO

- [x] Kolor akcentu profilu
- [x] Wyświetlanie klasycznego profilu jako tekstowy embed w przypadku błędu generacji profilu graficznego

## Lewa strona

- [x] Nickname
- [x] Tytuł
- [x] Staty ekonomii
  - [x] Ilość kapsli
  - [x] Ilość REP (pusta wartość, do dokończenia w #124)
  - [x] Ilość ~~koniczynek~~ itemów w eq
- [x] Staty aktywności z ostatnich 30 dni
  - [x] Ilość godzin na VC (pusta wartość, do dokończenia w #107)
  - [x] Ilość wiadomości TXT
  - [x] Wyświetlanie mniejszych fontów w odpowiedni sposób
- [x] Małżeństwo
  - [x] Ilość dni
  - [x] "z [User]"
  - [x] Szare serce i brak tekstu jeśli nie ma małżeństwa
  - [x] Usunięcie niepotrzebnej przerwy między "z" i "User123"
- [x] Data dołączenia na serwer
- [x] Data utworzenia konta

## Środek

- [x] Avatar
- [x] Avatar małżeństwa
- [x] Serce małżeństwa znika kiedy go nie ma
- [x] Ilość aktualnego expa/do następnego poziomu (pusta wartość, do dokończenia w #5)
- [x] Poziom (pusta wartość, do dokończenia w #5)

## Prawa strona

- [x] Tło
- [x] Ikonki w gablocie

**Comment by Daste745** [comment]
Czekamy na finalne designy profili. Można zacząć robić je zanim będziemy mieli wszystkie dane i uzupełnić luki w trakcie.
